Repository wonderfulsoftware/webring, pull requests merged in 2025-05, with the labels that each got.

#253 Add papazeal.com
  index.html
Labels: size:XS, lgtm

#254 Add iamthana.com
  index.html
Labels: size:XS, lgtm

#256 Add chompukyrc.com
  index.html
Labels: size:XS, lgtm

#257 Site fetcher upgrades
  .github/actions/site-fetcher-docker/action.yml
  .github/workflows/pr-reviewer.yml
  .github/workflows/site-updater.yml
  automation/pr-validator/README.md
  automation/pr-validator/index.js
  automation/site-fetcher/Dockerfile
  automation/site-fetcher/README.md
  automation/site-fetcher/docker-compose.yml
  automation/site-fetcher/jsconfig.json
  automation/site-fetcher/package.json
  automation/site-fetcher/src/index.js
  automation/site-fetcher/src/index.ts
  automation/site-fetcher/tsconfig.json
  automation/site-fetcher/yarn.lock
  automation/site-updater/README.md
  automation/site-updater/index.js
  dashboard.html
  package.json
  yarn.lock
Labels: size:XL

#258 add supakorn.info
  index.html
Labels: size:XS, lgtm

#259 webring cleanup on 2025-05-20
  CLAUDE.md
  index.html
Labels: size:M

#261 Update RSS feed URL for sujamess.com
  index.html
Labels: size:XS, lgtm
